---
name: devsociety
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus_web: ^1.0.0
  device_info_plus_windows: ^1.0.0
  flutter_animated_theme: ^0.9.0
  flutter_svg: ^0.19.3
  get_it: ^6.0.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
